---
title: "w7-notes"
author: "Spencer Zhang"
date: "11/4/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tigris)
library(sf)
library(tidyverse)
library(mapview)
library(readxl)
library(spdep)
library(spatialreg)
library(survey)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")
```


```{r}
sf_boundary <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME == "San Francisco")

ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

sf_pumas <-
  ca_pumas %>%
  st_centroid() %>%
  .[sf_boundary, ] %>%
  st_set_geometry(NULL) %>%
  left_join(ca_pumas %>% select (GEOID10)) %>%
  st_as_sf()
```

```{r}
temp <- tempfile()
download.file("https://www2.census.gov/programs-surveys/acs/data/pums/2019/1-Year/csv_hca.zip",destfile = temp)

pums_hca_2019_1yr <- read.csv(unzip(temp,"psam_h06.csv"))

unlink(temp)
```

```{r}
data <- pums_hca_2019_1yr %>%
  filter(PUMA %in% as.numeric(sf_pumas$PUMACE10)) %>%
  mutate(
    HINCP = as.numeric(HINCP),
    TEN = factor(TEN),
    MV = factor(MV)
    ) %>% select(
      HINCP,
      TEN,
      MV,
      starts_with("WGTP")
    ) %>%
  filter_all(all_vars(!is.na(.))) #helper function
```

```{r}
design <- svrepdesign(
  data = data,
  type = "ACS",
  repweight = data[, 5:84],
  weights = ~WGTP
)
```

```{r}
model <- svyglm(
  formula = HINCP ~TEN+MV,
  family = gaussian(), #normal distribution
  design = design
)
```

```{r}
summary(model)
```

```{r}
weighted_model <- data %>%
  lm(
    formula = HINCP ~TEN+MV,
    data = .,
    weights = WGTP
  )
```

```{r}
summary(weighted_model)
```

```{r}
replicates_model <-
  1:80 %>% 
  map_dfr(function(x){
    data %>% 
      rename(replicate = paste0("WGTP", x)) %>% 
      lm(
        formula = HINCP ~ TEN + MV,
        data = .,
        weights = replicate
      ) %>%
      .$coefficients %>%
      as.data.frame() %>%
      rownames_to_column()
  })
```

```{r}
weighted_model_summary <- replicates_model %>%
  rename(replicate = ".") %>%
  left_join(
    weighted_model$coefficients %>%
      as.data.frame() %>%
      rownames_to_column() %>%
      rename(base = ".")
  ) %>%
  group_by(rowname) %>%
  summarize(
    stderr = sqrt(4/80*sum((base - replicate)^2)),
    base = first(base)
  ) %>%
  select(rowname, base, stderr) #just to change order of columns
```

# demo2
```{r}
sf_healthcare <- read_csv("https://data.sfgov.org/api/views/jhsu-2pka/rows.csv?accessType=DOWNLOAD") #how to download csv from web sources

sf_healthcare_map <- sf_healthcare %>% 
  st_as_sf(wkt = "point", crs = 4326) #formatting geographic data to be readable in sf object

mapview(sf_healthcare_map)

#???
buffer <- sf_healthcare_map %>% 
  st_transform(26910) %>% 
  st_buffer(800) %>% 
  st_transform(4269)

mapview(buffer)
```

