---
title: "w8-notes"
author: "Spencer Zhang"
date: "11/11/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(StatMatch)
library(tidyverse)
library(censusapi)
library(leaflet)
library(tigris)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

acs_vars_2019_5yr <-
  listCensusMetadata(
    name = "2019/acs/acs5",
    type = "variables"
  )

bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_tracts <-
  tigris::tracts("CA", bay_county_names, cb = T, progress_bar = F)

bay_multiple_tract <- 
  getCensus(
    name = "acs/acs5",
    vintage = 2019,
    region = "tract:*",
    regionin = "state:06+county:001,013,041,055,075,081,085,095,097",
    vars = c(
      "B06009_001E",
      "B06009_002E",
      "B06009_003E",
      "B19001_001E",
      "B19001_014E",
      "B19001_015E",
      "B19001_016E",
      "B19001_017E",
      "B19001A_001E"
    )
  ) %>% 
  transmute(
    tract = paste0(state, county, tract),
    perc_college = 1 - (B06009_002E + B06009_003E) / B06009_001E,
    perc_over100k = (B19001_014E + B19001_015E + B19001_016E + B19001_017E) / B19001_001E,
    perc_white = B19001A_001E / B19001_001E
  ) %>% 
  filter(
    !is.na(perc_college), 
    !is.na(perc_over100k),
    !is.na(perc_white)
  )
```

```{r}
obs_matrix <-
  bay_multiple_tract %>% 
  select(
    perc_white, 
    perc_over100k,
    perc_college
  ) %>% 
  as.matrix()
```

```{r}
dist_matrix <- mahalanobis.dist(obs_matrix) #calculating "distances" of each row(as a vector)

rownames(dist_matrix) <- bay_multiple_tract$tract #renaming the col/row names to the census id the original vector refers to
colnames(dist_matrix) <- bay_multiple_tract$tract
```

```{r}
dist_matrix_pairmatch <- dist_matrix
diag(dist_matrix_pairmatch) <- NA

matched_pair_tract <-
  1:nrow(dist_matrix_pairmatch) %>% 
  map_dfr(function(x){
    
    min_index <- which(dist_matrix_pairmatch[x, ] == min(dist_matrix_pairmatch[x, ], na.rm = T)) #find the closet neighbor for one vector/row #the which() gives the row number
    data.frame(
      tract = bay_multiple_tract$tract[x], #put the tract id into the df as well
      matched_tract = bay_multiple_tract$tract[min_index] #put its closet neighbor in there as well
    )
  })
```

```{r}
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = bay_tracts %>% 
      filter(GEOID == matched_pair_tract[2,1])
  ) %>% 
  addPolygons(
    data = bay_tracts %>% 
      filter(GEOID == matched_pair_tract[2,2])
  ) %>% 
  addPolygons(
    data = bay_tracts %>% 
      filter(GEOID == matched_pair_tract[3,1]),
    color = "green"
  ) %>% 
  addPolygons(
    data = bay_tracts %>% 
      filter(GEOID == matched_pair_tract[3,2]),
    color = "green"
  ) %>% 
  addPolygons(
    data = bay_tracts %>% 
      filter(GEOID == matched_pair_tract[4,1]),
    color = "red"
  ) %>% 
  addPolygons(
    data = bay_tracts %>% 
      filter(GEOID == matched_pair_tract[4,2]),
    color = "red"
  )
```

```{r}
match_set_tract <- dist_matrix["06081611900", ] %>%
  as.data.frame() %>% 
  rownames_to_column() %>% 
  rename(
    tract = rowname,
    match = "."
  ) %>% 
  right_join(
    bay_multiple_tract
  ) %>% 
  arrange(match) %>% 
  .[1:21, ] %>% 
  left_join(bay_tracts %>% select(tract = GEOID)) %>% 
  st_as_sf()

leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = match_set_tract[1, ],
    color = "red"
  ) %>% 
  addPolygons(
    data = match_set_tract[-1, ]
  )
```


## example 2
```{r}
library(tigris)
library(tidyverse)
library(tidycensus)
library(sf)
library(censusapi)
library(leaflet)
library(StatMatch)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

ca_pumas <-
  pumas("CA", cb = T, progress_bar = F)

bay_county_names <-
  c(
    "Alameda",
    "Contra Costa",
    "Marin",
    "Napa",
    "San Francisco",
    "San Mateo",
    "Santa Clara",
    "Solano",
    "Sonoma"
  )

bay_counties <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME %in% bay_county_names)

bay_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[bay_counties, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()
```

```{r}
leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = bay_pumas,
    weight = 1,
    color = "gray",
    label = ~PUMACE10
  ) %>% 
  addMarkers(
    lng = -121.9415017,
    lat = 37.502171
  ) %>% 
  addPolygons(
    data = bay_pumas %>% 
      filter(PUMACE10 == "08504")
  )
```

